#       Copyright 2020-2021 IBM Corp, All Rights Reserved
#       Copyright 2022-2023 Kyndryl, All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#Deploy the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    app: {{ .Release.Name }}-stock-trader
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-portfolio"}{{- if .Values.account.enabled }}, {"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-account"}{{- end }}{{- if .Values.cashAccount.enabled }}, {"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-cash-account"}{{- end }}{{- if .Values.tradeHistory.enabled }}, {"apiVersion":"apps/v1","kind":"Deployment","name":"{{ .Release.Name }}-trade-history"}{{- end }}]'
    prism.subkind: Liberty
spec:
{{- if not .Values.broker.autoscale }}
  replicas: {{ .Values.broker.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
      annotations:
        git-repo: "https://github.com/IBMStockTrader/broker"
{{- if .Values.global.monitoring }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: "9080"
{{- end }}
{{- if .Values.global.istio }}
        maistra.io/expose-route: 'true'
        sidecar.istio.io/inject: 'true'
{{- end }}
    spec:
{{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ tpl .Values.global.pullSecretName . }}
{{- end }}
      containers:
      - name: broker
        image: "{{ .Values.broker.image.repository }}:{{ .Values.broker.image.tag }}"
        env:
          - name: AUTH_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: auth.type
          - name: TRACE_SPEC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: trace.spec
                optional: true
          - name: JWT_AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: jwt.audience
          - name: JWT_ISSUER
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: jwt.issuer
          - name: PORTFOLIO_URL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: portfolio.url
                optional: true
          - name: ACCOUNT_URL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: account.url
                optional: true
          - name: ACCOUNT_ENABLED
            value: {{ quote .Values.account.enabled }}
          - name: CASH_ACCOUNT_URL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: cashAccount.url
                optional: true
          - name: CASH_ACCOUNT_ENABLED
            value: {{ quote .Values.cashAccount.enabled }}
          - name: TRADE_HISTORY_URL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: tradeHistory.url
                optional: true
          - name: TRADE_HISTORY_ENABLED
            value: {{ quote .Values.tradeHistory.enabled }}
          - name: CQRS_ENABLED
            value: {{ quote .Values.global.cqrs }}
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: redis.url
                optional: true
          - name: CACHE_INTERVAL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: redis.cacheInterval
                optional: true
          - name: KAFKA_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.address
                optional: true
          - name: KAFKA_USER
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: kafka.user
                optional: true
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: kafka.apiKey
                optional: true
          - name: KAFKA_BROKER_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.brokerTopic
                optional: true
          - name: KAFKA_PORTFOLIO_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.portfolioTopic
                optional: true
          - name: KAFKA_ACCOUNT_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.accountTopic
                optional: true
          - name: KAFKA_CASH_ACCOUNT_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.cashAccountTopic
                optional: true
{{- if .Values.global.specifyCerts }}
          - name: cert_defaultTrustStore
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: ssl.certs
                optional: true
{{- end }}
{{- if .Values.global.jsonLogging }}
          - name: WLP_LOGGING_CONSOLE_FORMAT
            value: json
          - name: WLP_LOGGING_CONSOLE_SOURCE
            value: message,ffdc,trace
{{- end }}
{{- if .Values.global.disableLogFiles }}
          - name: WLP_LOGGING_MESSAGE_FORMAT
            value: json
          - name: WLP_LOGGING_MESSAGE_SOURCE
            value: none
{{- end }}
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
{{- if .Values.global.healthCheck }}
        startupProbe:
          httpGet:
            path: /health/started
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          periodSeconds: 15
          failureThreshold: 3
{{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
            ephemeral-storage: 256Mi
          requests:
            cpu: 250m
            memory: 256Mi
            ephemeral-storage: 32Mi
{{- if .Values.broker.autoscale }}
---
#Deploy the autoscaler
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-broker-hpa
  labels:
    app: stock-trader
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 120
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-broker
  minReplicas: {{ .Values.broker.replicas }}
  maxReplicas: {{ .Values.broker.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.broker.cpuThreshold }}
{{- end }}
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-broker-service
  labels:
    app: broker
{{- if .Values.global.monitoring }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9080"
{{- end }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: broker
{{- if .Values.global.ingress }}
---
#Configure the ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-broker-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    #ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/secure-backends: "true"
    #ingress.kubernetes.io/app-root: "/broker"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /broker
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-trader-service
            port:
              number: 9443
{{- end }}
{{- if .Values.global.route }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: broker
  name: {{ .Release.Name }}-broker
spec:
  port:
    targetPort: http
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}-broker-service
    weight: 100
  wildcardPolicy: None
---
{{- end }}
