#       Copyright 2021 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#Deploy the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-broker-cqrs
  labels:
    app: {{ .Release.Name }}-stock-trader
  annotations:
    prism.subkind: Liberty
spec:
  replicas: {{ .Values.brokerCQRS.replicas }}
  selector:
    matchLabels:
      app: broker-cqrs
  template:
    metadata:
      labels:
        app: broker-cqrs
      annotations:
        git-repo: "https://github.com/IBMStockTrader/broker-cqrs"
{{- if .Values.global.monitoring }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: "9080"
{{- end }}
{{- if .Values.global.istio }}
        maistra.io/expose-route: 'true'
        sidecar.istio.io/inject: 'true'
{{- end }}
    spec:
      containers:
      - name: broker-cqrs
        image: "{{ .Values.brokerCQRS.image.repository }}:{{ .Values.brokerCQRS.image.tag }}"
        env:
          - name: AUTH_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: auth.type
          - name: TRACE_SPEC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: trace.spec
                optional: true
          - name: KAFKA_PORTFOLIO_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: kafka.portfolioTopic
                optional: true
          - name: KAFKA_ACCOUNT_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: kafka.accountTopic
                optional: true
          - name: KAFKA_HISTORY_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: kafka.historyTopic
                optional: true
          - name: KAFKA_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: kafka.address
                optional: true
          - name: KAFKA_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-credentials
                key: kafka.user
                optional: true
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-credentials
                key: kafka.apiKey
                optional: true
          - name: JWT_AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: jwt.audience
          - name: JWT_ISSUER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: jwt.issuer
          - name: ACCOUNT_ENABLED
            value: {{ quote .Values.account.enabled }}
          - name: TRADE_HISTORY_ENABLED
            value: {{ quote .Values.tradeHistory.enabled }}
{{- if .Values.global.specifyCerts }}
          - name: cert_defaultTrustStore
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: ssl.certs
                optional: true
{{- end }}
{{- if .Values.global.jsonLogging }}
          - name: WLP_LOGGING_CONSOLE_FORMAT
            value: json
          - name: WLP_LOGGING_CONSOLE_SOURCE
            value: message,ffdc
{{- end }}
{{- if .Values.global.disableLogFiles }}
          - name: WLP_LOGGING_MESSAGE_FORMAT
            value: json
          - name: WLP_LOGGING_MESSAGE_SOURCE
            value: none
{{- end }}
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
{{- if .Values.global.healthCheck }}
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 3
{{- end }}
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 256Mi
{{- if .Values.brokerCQRS.autoscale }}
---
#Deploy the autoscaler
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-broker-cqrs-hpa
  labels:
    app: stock-trader
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-broker-cqrs
  minReplicas: {{ .Values.brokerCQRS.replicas }}
  maxReplicas: {{ .Values.brokerCQRS.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.brokerCQRS.cpuThreshold }}
{{- end }}
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-broker-cqrs-service
  labels:
    app: broker-cqrs
{{- if .Values.global.monitoring }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "9080"
{{- end }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: broker-cqrs
