#       Copyright 2023 Kyndryl, All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

{{- if .Values.cashAccount.enabled }}
#Deploy the pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cash-account
  labels:
    app: {{ .Release.Name }}-stock-trader
  annotations:
    prism.subkind: Spring
spec:
{{- if not .Values.cashAccount.autoscale }}
  replicas: {{ .Values.cashAccount.replicas }}
{{- end }}
  selector:
    matchLabels:
      app: cash-account
  template:
    metadata:
      labels:
        app: cash-account
      annotations:
        git-repo: "https://github.com/IBMStockTrader/cash-account"
{{- if .Values.vault.enabled }}
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-stocktrader-secrets.txt: {{ .Values.vault.path }}
        vault.hashicorp.com/agent-inject-template-stocktrader-secrets.txt: |
          {{"{{"}}- with secret "{{ .Values.vault.path }}" -{{"}}"}}
          export JDBC_ID={{"{{"}} .Data.data.jdbcId {{"}}"}}
          export JDBC_PASSWORD={{"{{"}} .Data.data.jdbcPassword {{"}}"}}
          export REDIS_URL={{"{{"}} .Data.data.redisUrl {{"}}"}}
          export KAFKA_USER={{"{{"}} .Data.data.kafkaUser {{"}}"}}
          export KAFKA_API_KEY={{"{{"}} .Data.data.kafkaApiKey {{"}}"}}
          {{"{{"}}- end -{{"}}"}}
        vault.hashicorp.com/role: {{ .Values.vault.role }}
{{- end }}
{{- if .Values.global.monitoring }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: "8080"
{{- end }}
{{- if .Values.global.istio }}
        sidecar.istio.io/inject: 'true'
{{- end }}
    spec:
{{- if .Values.global.pullSecret }}
      imagePullSecrets:
      - name: {{ tpl .Values.global.pullSecretName . }}
{{- end }}
      containers:
      - name: cash-account
        image: "{{ .Values.cashAccount.image.repository }}:{{ .Values.cashAccount.image.tag }}"
{{- if .Values.vault.enabled }}
        args:
          - sh
          - '-c'
          - source /vault/secrets/stocktrader-secrets.txt && /opt/ol/helpers/runtime/docker-server.sh /opt/ol/wlp/bin/server run defaultServer
{{- end }}
        env:
          - name: AUTH_TYPE
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: auth.type
          - name: TRACE_SPEC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: trace.spec
                optional: true
          - name: JDBC_KIND
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: database.kind
          - name: JDBC_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: database.host
          - name: JDBC_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: database.port
          - name: JDBC_DB
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: database.db
          - name: JDBC_SSL
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: database.ssl
{{- if not .Values.vault.enabled }}
          - name: JDBC_ID
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: database.id
          - name: JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: database.password
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: redis.url
          - name: KAFKA_USER
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: kafka.user
                optional: true
          - name: KAFKA_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ tpl .Values.global.secretName . }}
                key: kafka.apiKey
                optional: true
{{- end }}
          - name: KAFKA_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.address
                optional: true
          - name: KAFKA_CASH_ACCOUNT_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.cashAccountTopic
                optional: true
          - name: KAFKA_BROKER_TOPIC
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.brokerTopic
                optional: true
          - name: KAFKA_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: kafka.address
                optional: true
          - name: JWT_AUDIENCE
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: jwt.audience
          - name: JWT_ISSUER
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: jwt.issuer
          - name: CQRS_ENABLED
            value: {{ quote .Values.global.cqrs }}
{{- if .Values.global.specifyCerts }}
          - name: cert_defaultTrustStore
            valueFrom:
              configMapKeyRef:
                name: {{ tpl .Values.global.configMapName . }}
                key: ssl.certs
                optional: true
{{- end }}
{{- if .Values.global.jsonLogging }}
          - name: WLP_LOGGING_CONSOLE_FORMAT
            value: json
          - name: WLP_LOGGING_CONSOLE_SOURCE
            value: message,ffdc,trace
{{- end }}
{{- if .Values.global.disableLogFiles }}
          - name: WLP_LOGGING_MESSAGE_FORMAT
            value: json
          - name: WLP_LOGGING_MESSAGE_SOURCE
            value: none
{{- end }}
        ports:
          - containerPort: 8080
          - containerPort: 8443
        imagePullPolicy: Always
{{- if .Values.global.healthCheck }}
        startupProbe:
          httpGet:
            path: /actuator/startup
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          periodSeconds: 15
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          periodSeconds: 15
          failureThreshold: 3
{{- end }}
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
            ephemeral-storage: 256Mi
          requests:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 32Mi
{{- if .Values.cashAccount.autoscale }}
---
#Deploy the autoscaler
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-cash-account-hpa
  labels:
    app: stock-trader
spec:
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Min
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      selectPolicy: Max
      policies:
        - type: Percent
          value: 100
          periodSeconds: 120
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-cash-account
  minReplicas: {{ .Values.cashAccount.replicas }}
  maxReplicas: {{ .Values.cashAccount.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.cashAccount.cpuThreshold }}
{{- end }}
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cash-account-service
  labels:
    app: cash-account
{{- if .Values.global.monitoring }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: "8080"
{{- end }}
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: cash-account
{{- end }}