#       Copyright 2017 IBM Corp All Rights Reserved

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

{{- if .Values.notification-twitter.enabled }}
#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-twitter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification
        solution: stock-trader
        version: twitter
    spec:
      containers:
      - name: notification-twitter
        image: "{{ .Values.notification-twitter.image.repository }}:{{ .Values.notification-twitter.image.tag }}"
        env:
          - name: TWITTER_CONSUMER_KEY
            valueFrom:
              secretKeyRef:
                name: twitter
                key: consumerKey
          - name: TWITTER_CONSUMER_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter
                key: consumerSecret
          - name: TWITTER_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: twitter
                key: accessToken
          - name: TWITTER_ACCESS_TOKEN_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter
                key: accessTokenSecret
          - name: JWT_AUDIENCE
            valueFrom:
              secretKeyRef:
                name: jwt 
                key: audience
          - name: JWT_ISSUER
            valueFrom:
              secretKeyRef:
                name: jwt
                key: issuer
        ports:
          - containerPort: 9080
          - containerPort: 9443
        imagePullPolicy: Always
{{- end }}
